### ISSUE TITLE
Requires_grad of src_pred_mask

### ISSUE THREAD

**Issue by XMU-qcj** [hxwork/OMNet_Pytorch#6]
When num_iter>3, src_pred_mask becomes a tensor that requires gradient, and then an error will be reported in the  function generate_overlap_mask
RuntimeError: logical_not(): functions with out=... arguments don't support automatic differentiation, but one of the arguments requires grad.

**Comment by hxwork** [comment]
Hi,

Have you changed any code in this repo? I haven't found the same error. `src_pred_mask` is used in a hard way since the `argmax` operation will change it to a binary map. Besides, the function`generate_overlap_mask` is just used to generate the ground truth masks at each iteration, which have no need to require gradients or gradients backward.

**Comment by XMU-qcj** [comment]
> Hi,
> 
> Have you changed any code in this repo? I haven't found the same error. `src_pred_mask` is used in a hard way since the `argmax` operation will change it to a binary map. Besides, the function`generate_overlap_mask` is just used to generate the ground truth masks at each iteration, which have no need to require gradients or gradients backward.

Sorry, there may be differences in the pytorch versions we use. I added a detach to src_pred_mask, which should solve the problem, thank you

**Comment by hxwork** [comment]
Okay. I will close this issue.
